### ISSUE TITLE
CommandHistory can't save the new function args format

### ISSUE THREAD

**Issue by eeue56** [NoRedInk/slack-today-i-did#29]
```
TypeError: Object of type 'UnionMeta' is not JSON serializable
Traceback (most recent call last):
  File "main.py", line 29, in <module>
    main()
  File "main.py", line 22, in main
    client = setup()
  File "main.py", line 18, in setup
    return TodayIDidBot(data['token'], rollbar_token=data['rollbar-token'], elm_repo=repo)
  File "/home/ec2-user/slack-today-i-did/slack_today_i_did/bot_file.py", line 47, in __init__
    self._setup_command_history()
  File "/home/ec2-user/slack-today-i-did/slack_today_i_did/bot_file.py", line 65, in _setup_command_history
    self.command_history.load_from_file(known_functions, self.command_history_file)
  File "/home/ec2-user/slack-today-i-did/slack_today_i_did/command_history.py", line 13, in wrapper
    f(self, *args, **kwargs)
  File "/home/ec2-user/slack-today-i-did/slack_today_i_did/command_history.py", line 54, in load_from_file
    as_json = json.load(f)
  File "/usr/local/lib/python3.6/json/__init__.py", line 298, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/local/lib/python3.6/json/__init__.py", line 353, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 817 (char 816)

```

**Comment by ento** [comment]
taking a look
